### PR TITLE
add support for comparing ggplot2 objects

### PR DESCRIPTION
**Pull request by richarddmorey**
Initial try add adding support for ggplot2 objects

### CODE REVIEW

**Comment by xvrdm** [comment]
Hi Richard, Thanks for the PR!

As said on Twitter, I agree about your suggested split of all the ggplot2 related code into a dedicated function. We could simply keep an optional warning in the main ricv() if the user provided a value for `img1`/`img2` that has the classes of a ggplot.

And I would also advise to only add ggplot2 as a 'Suggests' dependency and warn the user when the package is missing.

**Comment by richarddmorey** [comment]
Would you like me to redo the pull request with those changes?

**Comment by xvrdm** [comment]
If you want to, yes. Otherwise please just let me know. 
I think the right implementation would be a call in `ricv` to a S3 method named something like `prepare_img()`. Based on the type of image passed (url, path, ggplot2), it would apply the correct preformatting.

**Comment by richarddmorey** [comment]
> If you want to, yes. Otherwise please just let me know. I think the right implementation would be a call in `ricv` to a S3 method named something like `prepare_img()`. Based on the type of image passed (url, path, ggplot2), it would apply the correct preformatting.

Yes, that makes sense. I'm not sure when I'll have time to do this fully, but I'll close this up and open an issue instead, where further discussion can go.

**Pull request closed without merging**
